# Generated by Django 5.0 on 2026-01-10 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vulnerability", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefenseTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("firewall", "Firewall"),
                            ("ids_ips", "IDS/IPS"),
                            ("encryption", "Encryption"),
                            ("access_control", "Access Control"),
                            ("patch_management", "Patch Management"),
                            ("security_monitoring", "Security Monitoring"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "effectiveness_score",
                    models.FloatField(help_text="Score from 0-100"),
                ),
                (
                    "implementation_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("difficult", "Difficult"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("implementation_time", models.CharField(max_length=100)),
                ("prerequisites", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "defense_technique",
            },
        ),
        migrations.CreateModel(
            name="DefenseRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority_score", models.FloatField()),
                (
                    "recommended_by",
                    models.CharField(default="ML Model", max_length=100),
                ),
                ("confidence_score", models.FloatField()),
                ("justification", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defense_recommendations",
                        to="vulnerability.vulnerability",
                    ),
                ),
                (
                    "defense_technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="defense.defensetechnique",
                    ),
                ),
            ],
            options={
                "db_table": "defense_recommendation",
                "ordering": ["-priority_score"],
            },
        ),
        migrations.CreateModel(
            name="DefenseImplementation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("success_rate", models.FloatField(blank=True, null=True)),
                (
                    "implemented_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="defense.defenserecommendation",
                    ),
                ),
            ],
            options={
                "db_table": "defense_implementation",
            },
        ),
    ]
